site_name: Call.Report
site_url: https://call.report/
theme:
    name: material
nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Code: 'code.md'
    - Data Sources:
        - Federal Reserve:
          - UBPR: 'data-sources.md#ubpr'
        - FDIC: 'data-sources.md'